//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeRange.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState ActiveWindowSelectorState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["ActiveWindowSelectorState"]));
            }
            set {
                this["ActiveWindowSelectorState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ActiveWindowSelectorLocation {
            get {
                return ((global::System.Drawing.Point)(this["ActiveWindowSelectorLocation"]));
            }
            set {
                this["ActiveWindowSelectorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ActiveWindowSelectorSize {
            get {
                return ((global::System.Drawing.Size)(this["ActiveWindowSelectorSize"]));
            }
            set {
                this["ActiveWindowSelectorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState ArrangementEditState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["ArrangementEditState"]));
            }
            set {
                this["ArrangementEditState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ArrangementEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["ArrangementEditLocation"]));
            }
            set {
                this["ArrangementEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ArrangementEditSize {
            get {
                return ((global::System.Drawing.Size)(this["ArrangementEditSize"]));
            }
            set {
                this["ArrangementEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState DeRangeMainState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["DeRangeMainState"]));
            }
            set {
                this["DeRangeMainState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DeRangeMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["DeRangeMainLocation"]));
            }
            set {
                this["DeRangeMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DeRangeMainSize {
            get {
                return ((global::System.Drawing.Size)(this["DeRangeMainSize"]));
            }
            set {
                this["DeRangeMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState LocationEditState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["LocationEditState"]));
            }
            set {
                this["LocationEditState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["LocationEditLocation"]));
            }
            set {
                this["LocationEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LocationEditSize {
            get {
                return ((global::System.Drawing.Size)(this["LocationEditSize"]));
            }
            set {
                this["LocationEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowEditState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowEditState"]));
            }
            set {
                this["WindowEditState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowEditLocation"]));
            }
            set {
                this["WindowEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size WindowEditSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowEditSize"]));
            }
            set {
                this["WindowEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowLocationSelectorState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowLocationSelectorState"]));
            }
            set {
                this["WindowLocationSelectorState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocationSelectorLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocationSelectorLocation"]));
            }
            set {
                this["WindowLocationSelectorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size WindowLocationSelectorSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowLocationSelectorSize"]));
            }
            set {
                this["WindowLocationSelectorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAtStartup {
            get {
                return ((bool)(this["RunAtStartup"]));
            }
            set {
                this["RunAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState OptionsEditState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["OptionsEditState"]));
            }
            set {
                this["OptionsEditState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size OptionsEditSize {
            get {
                return ((global::System.Drawing.Size)(this["OptionsEditSize"]));
            }
            set {
                this["OptionsEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OptionsEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["OptionsEditLocation"]));
            }
            set {
                this["OptionsEditLocation"] = value;
            }
        }
    }
}
